#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_corpus.py — turn the primary sources in assets/intake/trials/*.json into the
corpus the app carries, and splice it into index.html between the CORPUS markers.

This is a BUILD-TIME step, not a backend. Nothing listens on a port, nothing is
deployed, and the published artifact makes no network call: the corpus ends up
inline in index.html and is therefore loaded at page load like any other script.

What it emits per record, and nothing more:

  - nctId, briefTitle, sponsor, phase, status, conditions   (real registry fields)
  - minimumAge / maximumAge / sex                           (real registry fields)
  - enrollment                                              (real registry field)
  - nearestSite + siteDistanceMi, computed from the registry's own geoPoint
  - eligibilityCriteria: THE RAW TEXT, VERBATIM

The eligibility text is copied byte for byte — original line breaks, original bullet
markers, original typos. It is the parser's input and the audit table's quoted
"original wording", so cleaning it up here would quietly destroy the thing the whole
project is built to demonstrate.

Deliberately NOT emitted: anything shaped like {op, threshold}. Turning this text
into predicates is the parser's job, done by code at runtime, in front of the viewer.
A hand-structured corpus would be that job done by hand, which is exactly what the
2026-10-06 rewrite set out to delete.

Usage:  python scripts/build_corpus.py
"""
import json, io, os, re, sys, math, datetime

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT   = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INTAKE = os.path.join(ROOT, "assets", "intake", "trials")
INDEX  = os.path.join(ROOT, "index.html")

BEGIN = "  /* ===== CORPUS:BEGIN — generated by scripts/build_corpus.py. Do not hand-edit. ===== */"
END   = "  /* ===== CORPUS:END ===== */"

# Where "travel distance" is measured from. This is an app setting, not a person:
# the synthetic patient was deleted on 2026-10-06 and nothing here stands in for one.
HOME = {"label": "Philadelphia, PA", "lat": 39.9526, "lon": -75.1652}


def miles(lat1, lon1, lat2, lon2):
    """Great-circle distance. The registry publishes a geoPoint per location, so the
    distance shown on screen is computed from real coordinates, not typed in."""
    r = 3958.7613
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp, dl = math.radians(lat2 - lat1), math.radians(lon2 - lon1)
    a = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * r * math.asin(math.sqrt(a))


def nearest_site(p):
    best = None
    for loc in p.get("contactsLocationsModule", {}).get("locations", []) or []:
        g = loc.get("geoPoint")
        if not g:
            continue
        d = miles(HOME["lat"], HOME["lon"], g["lat"], g["lon"])
        if best is None or d < best[0]:
            city = ", ".join(x for x in [loc.get("city"), loc.get("state"), loc.get("country")] if x)
            best = (d, city)
    return best


def record(path):
    d = json.load(io.open(path, encoding="utf-8"))
    p = d["protocolSection"]
    idm, stm, em = p["identificationModule"], p["statusModule"], p["eligibilityModule"]
    dm = p.get("designModule", {})

    crit = em.get("eligibilityCriteria") or ""
    if not crit.strip():
        raise ValueError("%s has no eligibilityCriteria" % idm["nctId"])

    out = {
        "nctId":      idm["nctId"],
        "briefTitle": idm.get("briefTitle", ""),
        "sponsor":    p.get("sponsorCollaboratorsModule", {}).get("leadSponsor", {}).get("name", ""),
        "status":     stm.get("overallStatus", ""),
        # the registry's own value. An observational study has no phase, and the
        # corpus says so with an empty string rather than inventing an "N/A".
        "phase":      ", ".join(dm.get("phases") or []),
        "studyType":  dm.get("studyType", ""),
        "conditions": p.get("conditionsModule", {}).get("conditions", []) or [],
        "enrollment": (dm.get("enrollmentInfo") or {}).get("count"),
        "minimumAge": em.get("minimumAge", ""),
        "maximumAge": em.get("maximumAge", ""),
        "sex":        em.get("sex", "ALL"),
        # verbatim, and never anything else
        "eligibilityCriteria": crit,
    }

    site = nearest_site(p)
    if site:
        out["nearestSite"] = site[1]
        out["siteDistanceMi"] = int(round(site[0]))
    return out


def main():
    files = sorted(f for f in os.listdir(INTAKE) if f.endswith(".json"))
    records = [record(os.path.join(INTAKE, f)) for f in files]
    records.sort(key=lambda r: r["nctId"])

    # ---- integrity checks, because a corpus that lies is worse than no corpus ----
    seen = set()
    for r in records:
        assert r["nctId"] not in seen, "duplicate %s" % r["nctId"]
        seen.add(r["nctId"])
        assert r["eligibilityCriteria"].strip(), "%s lost its criteria" % r["nctId"]
    # the raw text must survive the round trip into the generated JS, exactly
    for f, r in zip(files, records):
        raw = json.load(io.open(os.path.join(INTAKE, f), encoding="utf-8"))
        want = raw["protocolSection"]["eligibilityModule"]["eligibilityCriteria"]
        got = json.loads(json.dumps(r["eligibilityCriteria"]))
        assert got == want, "%s criteria text changed in transit" % r["nctId"]

    body = json.dumps(records, ensure_ascii=False, indent=2)
    body = "\n".join(("  " + ln).rstrip() for ln in body.split("\n"))

    block = "\n".join([
        BEGIN,
        "  /* %d real ClinicalTrials.gov records, downloaded %s." % (len(records), TODAY),
        "     Primary sources live in assets/intake/trials/ — one unmodified API response",
        "     per record. eligibilityCriteria below is that response's text VERBATIM:",
        "     original line breaks, original bullet markers, original typos. It is parsed",
        "     into rules at runtime by parseCriteria(); nothing here is pre-structured. */",
        "",
        "  /* Every siteDistanceMi below is measured from here. Emitted with the corpus",
        "     rather than typed into the page, so the label on screen and the origin the",
        "     distances were computed from cannot drift apart. */",
        "  var DISTANCE_ORIGIN = %s;" % json.dumps(HOME["label"], ensure_ascii=False),
        "",
        "  var CORPUS =",
        body + ";",
        END,
    ])

    src = io.open(INDEX, encoding="utf-8").read()
    i, j = src.find(BEGIN), src.find(END)
    if i < 0 or j < 0:
        raise SystemExit("CORPUS markers not found in index.html — add them first")
    src = src[:i] + block + src[j + len(END):]
    io.open(INDEX, "w", encoding="utf-8", newline="").write(src)

    print("corpus: %d records -> index.html" % len(records))
    print("criteria text: %d chars total, %d max (%s)" % (
        sum(len(r["eligibilityCriteria"]) for r in records),
        max(len(r["eligibilityCriteria"]) for r in records),
        max(records, key=lambda r: len(r["eligibilityCriteria"]))["nctId"]))
    print("index.html is now %d bytes" % len(src.encode("utf-8")))


# The date the records were DOWNLOADED, not the date this script was last run.
# date.today() silently rewrote the provenance line on every rebuild — a rebuild
# that re-downloads nothing has no business moving the date a reader uses to go
# check the registry. The newest intake file's mtime is when the corpus actually
# landed; assets/intake/trials/README.md carries the full range.
def downloaded_on():
    files = [os.path.join(INTAKE, f) for f in os.listdir(INTAKE) if f.endswith(".json")]
    return datetime.date.fromtimestamp(max(os.path.getmtime(f) for f in files)).isoformat()


TODAY = downloaded_on()

if __name__ == "__main__":
    main()
